ALTER TABLE task_movements
MODIFY COLUMN coluna_origem ENUM('EM_ESPERA', 'EM_PROGRESSO', 'CONCLUIDO', 'EM_ANALISE', 'APROVADO');

ALTER TABLE task_movements
MODIFY COLUMN coluna_destino ENUM('EM_ESPERA', 'EM_PROGRESSO', 'CONCLUIDO', 'EM_ANALISE', 'APROVADO');
